name: Sponsors CD

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: rrbutani/use-nix-shell-action@v1
        with:
          devShell: ./sponsors#
          exportEnv: false
          script: |
            export SPONSORKIT_GITHUB_TOKEN=${{ secrets.PROFILE_TOKEN }}
            export SPONSORKIT_GITHUB_LOGIN=StarLederer
            cd sponsors
            pnpm i
            pnpm run build

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Deploy sponsors"
          add: "www/sponsors"

      - run: git subtree push --prefix www origin www

