name: Sponsors CD

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          token: ${{ secrets.PROFILE_TOKEN }}

      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: rrbutani/use-nix-shell-action@v1
        with:
          devShell: ./sponsors#
          exportEnv: false
          script: |
            export SPONSORKIT_GITHUB_TOKEN=${{ secrets.PROFILE_TOKEN }}
            export SPONSORKIT_GITHUB_LOGIN=StarLederer
            cd sponsors
            pnpm i
            pnpm run build

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add www
          git commit -m "Deploy"
          git subtree push --prefix www origin www
