name: Sponsors CD

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PROFILE_TOKEN }}

      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: rrbutani/use-nix-shell-action@v1
        with:
          devShell: ./sponsors#
          exportEnv: false
          script: |
            export SPONSORKIT_GITHUB_TOKEN=${{ secrets.PROFILE_TOKEN }}
            export SPONSORKIT_GITHUB_LOGIN=StarLederer
            cd sponsors
            pnpm i
            pnpm run build

      - uses: EndBug/add-and-commit@v9
        with:
          add: www
          message: Deploy
          commit: --allow-empty
          push: false

      - run: git subtree push --prefix www origin www
