name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: workflow/nix-shell-action@v3
        with:
          working-directory: ./sponsors
          script: |
            ls
            pnpm -v
            ls

      - run: ls
      - run: ls sponsors
      - run: ls www/sponsors

