name: Sponsors CD

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: rrbutani/use-nix-shell-action@v1
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: StarLederer
        with:
          devShell: ./sponsors#
          exportEnv: false
          script: |
            echo $SPONSORKIT_GITHUB_LOGIN
            export SPONSORKIT_GITHUB_TOKEN=${{ secrets.PROFILE_TOKEN }}
            export SPONSORKIT_GITHUB_LOGIN=StarLederer
            cd sponsors
            pnpm i
            pnpm run build

      - run: ls www/sponsors

