name: Windblade CD

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: git clone --recurse-submodules https://github.com/StarLederer/windblade.git .tmp

      - name: Build
        uses: rrbutani/use-nix-shell-action@v1
        with:
          devShell: ./.tmp#
          exportEnv: false
          script: |
            cd .tmp
            ls
            ls brand
            cd unocss
            pnpm i
            pnpm run build
            cd ../docs
            pnpm i
            pnpm run build

      - name: Copy artifacts
        run: |
          rm -rf windblade
          mv -f .tmp/docs/dist windblade

      - uses: EndBug/add-and-commit@v9
        with:
          add: www
          message: Deploy
          commit: --allow-empty
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
