name: Windblade CD

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PROFILE_TOKEN }}

      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: git clone https://github.com/StarLederer/windblade.git

  build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: rrbutani/use-nix-shell-action@v1
        with:
          devShell: ./windblade#
          exportEnv: false
          script: |
            cd windblade
            cd unocss
            pnpm i
            pnpm run build
            cd ../docs
            pnpm i
            pnpm run build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Copy artifacts
      - run: |
        rm -rf www/windblade
        mv -f windblade/docs/dist www/windblade

      - uses: EndBug/add-and-commit@v9
        with:
          add: www
          message: Deploy
          commit: --allow-empty

      - run: git subtree push --prefix www origin www
